### ISSUE TITLE
Incompatible version between github and npm

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#12]
Hi, 

I just create a new project with vulcain-cli. I want to use rabbitMQService but there is a mistake.
On the github project at [https://github.com/vulcainjs/vulcain-corejs/blob/master/src/bus/rabbitAdapter.ts](https://github.com/vulcainjs/vulcain-corejs/blob/master/src/bus/rabbitAdapter.ts)  on the constructor there is 

```js
   constructor(private address: string) {
        if (!this.address)
            throw new Error("Address is required for RabbitAdapter");

        if (!address.startsWith("amqp://"))
            this.address = "amqp://" + address;
    }
```

But when i made `npm i vulcain-corejs` with the same version `1.1.130` into the folder `dist/bus/rabbitAdapter.js` we have 

```js
 constructor(address) {
        this.address = address;
        this.domainHandlers = new Map();
        this.initialized = false;
        if (!this.address)
            throw new Error("Address is required for RabbitAdapter");
        if (!address.startsWith("amqp://"))
            this.address = "amqp://" + address;
        this.address += "/" + system_1.System.environment;
    }
```
So i think, you need only to compile the Typescript to have the same version between npm & github.

**Comment by malain** [comment]
done
