### ISSUE TITLE
Cannot connect to MongoDB

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#16]
Hi, 

I tried to connect to my mongodb server, but nothing happened.
I registrer my configuration  `container.useMongoProvider(myUri)` but when i'm debbuging the source code in `container.js` file on method `useMongoProvider` the breakpoint is called. I have the log who tell me the component are register
```sh
26 Jun 12:14:46 - INFO: Register instance component Provider as MongoProvider - {"service":"user-service","version":"1.0","kind":"Log","source":"MacBook-Pro-de-Johan.local","timestamp":1498472086587000,"message":"INFO: Register instance component Provider as MongoProvider"}
```

But when i put a breakpoint into the contructor of `MongoProvider` class, it's never called.

**Comment by malain** [comment]
MongoProvider constructor is called on the first request.

**Comment by workfel** [comment]
Thank you, i thought it was on startup.
