### ISSUE TITLE
Command no return error

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#20]
Hi, 

I made a Http request from a `AbstractHttpCommand` class, during the request i have no response from it, and i have remove the `fallbackAsync`method, and the server still pending on request.

It's mandatory to have the `fallback` method ?

To solve it i put trycatch, it's the good way, or the command should be this automatically ? 
```js
   async runAsync(user: User): Promise<RocketChatUser> {
        try {
            let userToCreate: RocketChatToCreateUser = this.service.convertUser(user);
            let response = await this.postAsync(`${this.hostRocketChatGateway.value}/api/user.createuser`, userToCreate);
            return response.body.value;
        } catch (error) {
            throw { message: error };
        }

    }
```

Thx

**Comment by malain** [comment]
Fallback must be provided only if you want a compensation.
You do not have to catch an error in your command except to transform an error without a message property (which must be a string). 
In your example, you can remove the try..catch

**Comment by workfel** [comment]
Ok thank you.
But in my example, if i remove the `try catch` the error are not returned. The server return 
```json
{
    "tenant": "vulcain",
    "schema": "User",
    "action": "createuser",
    "domain": "mydomain",
    "status": "Error",
    "correlationId": "59f2fcea4790452eac4673f4057b42eb",
    "error": {
  
    }
}
```

Because the error returned form HTTP request it's : 
```json
{ 
 "errorMessage" : "string"
}
```
