### ISSUE TITLE
Only one Consumer by EventHandler ?

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#28]
Hi,

I use the `@EventHandler` annotation and i have put 3 Consumer into this class, but when i'm starting the server, only the first consumer is loaded.
It's right ? 

To solve it i created 3 `@EventHandler` which this own Consumer.

It's a bug or it's the good way ?

Thx

**Comment by malain** [comment]
it's a bug. You can now (v 144) create many consumers in the same event handler
