### ISSUE TITLE
support for passing arrays as parameters

### ISSUE THREAD

**Issue by mrik974** [vulcainjs/vulcain-corejs#30]
Hi,
Are there plans for supporting arrays of `Basic types` in `QueryHandlers`' parameters ?

**Comment by malain** [comment]
All vulcain queries (or actions) accept only an object as parameter. This object (defined as a Model) contains all parameters which can be an array.
To send an array value with a GET, you must use this syntax :
/myquery?array1=x&array1=y&array1=z where array1 is the parameter name.
