### ISSUE TITLE
Model attributes of type `any` have no value

### ISSUE THREAD

**Issue by mrik974** [vulcainjs/vulcain-corejs#31]
Hi!

I'm trying to use this model in vulcainjs

```
@Model({ storageName: 'notification-service-Notification' })
export class Notification {

    @Property({ type: 'string', unique: true, isKey: true })
    id?: string;

    @Property({ type: 'string', required: true })
    userId?: string;

    @Property({ type: 'string', required: true })
    type?: string;

    @Property({ type: 'any', required: true})
    data?: any;

}
```

The service starts normally, and it seems that ` @Property({type: 'any'})` will be taken into account (if I put `object` instead of `any` for example, the service refuses to start).

When I try to create an object of type `Notification` I get this error message (due to the `required: true` : 

```
{
        "message": "Property 'data' is required.",
        "property": "data"
}
```

Here's my JSON payload however (the ID is created in the Handler): 
```
{
  "userId": "12345",
  "type": "invitation",
  "data": {"test":"testvalue"}
}
```
I also tried using primitives ( `"data":"test"` or `"data":1234`) but I obtain the same result. It looks like `@Property({type:'any'})` doesn't work.

**Comment by malain** [comment]
You must use @Reference instead of @Property for complex type (But that can be a good idea to use your syntax in this case).
I keep this issue open

**Comment by mrik974** [comment]
In fact I want this object to be anything. It would stand along the notification as a helper for the user interface.

Emeric LEBON
06 51 00 72 93
________________________________

**Comment by rascaille** [comment]
Emeric, Be careful, there is your phone number in the signature of your message.
About "any", in the documentation : 
With @refererence, ["You can use any for referencing anonymous item."](http://www.vulcainjs.org/reference/domain/)

Are you tested ?

**Comment by mrik974** [comment]
Thank you @rascaille for the warning! 
I haven't tested it, as I hadn't seen it in fact. Will give it a try ASAP.

**Comment by aguerot** [comment]
also in your model
`@Property({ type: 'string', required: true })
userId?: string;` 
decorating your property as required in the model but allowing it to be null with ? suffix prevents the compiler to let you know when missing required property
