### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by workfel** [vulcainjs/vulcain-corejs#32]
Hi, 

I tried to use pagination, but it seem isn't working.

I created a DefaultQueryHandler and when i check the service description i have this verb.
```js
{
"schema": "Contacts",
"kind": "query",
"verb": "contacts.all",
"outputType": "many",
"description": "Get all entities",
"action": "all",
"scope": "?",
"async": false,
"outputSchema": "Contacts"
}
```

When i launch `.../api/contacts.all` i getting all my record (8).
And for use pagination i use this url `.../api/contacts.all?maxByPage=3` but i getting no record.

It's my request who is malformed ? 

Thx

**Comment by malain** [comment]
The correct syntax is .../api/contacts.all?$maxByPage=3 (maxByPage and page must be prepend with $) otherwise maxByPage is considered as a query filter (select only contacts with property maxByPage equals to 3).
